version: '3.4'

services:
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
        volumes:
            - .docker/data/db:/var/lib/mysql
            - .docker/mysql/my.cnf:/etc/mysql/conf.d/conf-mysql.cnf:ro
        environment:
            - MYSQL_ROOT_PASSWORD=jdm
            - MYSQL_PASSWORD=jdm
            - MYSQL_DATABASE=jdm
            - MYSQL_USER=jdm

    php:
        build:
            context: .
            target: symfony_php
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
            - .:/srv/app:cached
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s

    caddy:
        build:
            context: .
            target: symfony_caddy
        depends_on:
            - php
        restart: unless-stopped
        volumes:
            - .:/srv/app
            - php_socket:/var/run/php
            - caddy_data:/data
            - caddy_config:/config
        ports:
            # HTTP
            - target: 80
              published: 80
              protocol: tcp

            # HTTPS
            - target: 443
              published: 443
              protocol: tcp

            # HTTP/3
            - target: 443
              published: 443
              protocol: udp

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - db

    mailer:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:25"

volumes:
    php_socket:
    caddy_data:
    caddy_config:
